version: "3.3"
services:
  mongo:
    image: mongo:5.0.5
    ports:
    - 27017:27017
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
    - 3000:3000
    environment:
    - MONGO_URL=mongodb://mongo:27017/weather
    command: npm run start
  

